#
# The Short URL User Production Service
# (Copyright 2024 by Richard Klein)
#
version = 0.1
[default.deploy.parameters]
stack_name = "short-url-user-service-prod"
resolve_s3 = true
s3_prefix = "short-url-user-service-prod"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = false
confirm_changeset = false
